/**
 * pricing-engine.ts — Single source of truth for price calculation.
 *
 * ALL percentages are decimals in range 0-1 (e.g. 0.10 = 10%).
 * The UI layer converts display values before calling this module.
 *
 * This module is pure (no I/O, no framework deps, no Supabase).
 * It is shared between web-app (preview) and edge function (persist).
 *
 * >>> DO NOT EDIT THIS FILE DIRECTLY <<<
 * Source of truth: web-app/src/utils/pricing-engine.ts
 * Sync with: npm run sync-pricing-engine
 */

// ---------------------------------------------------------------------------
// Labor % company-wide (legacy — deprecated)
// ---------------------------------------------------------------------------

const DEFAULT_DAYS_PER_MONTH = 22

/**
 * @deprecated Motor agora recebe laborCostMonthly + workload diretamente.
 * Mantido apenas para compatibilidade de imports existentes.
 */
export function computeLaborPctCompany(
  laborMonthly: number,
  totalEmployees: number,
  hoursPerMonth: number,
  daysPerMonth: number = DEFAULT_DAYS_PER_MONTH,
): number {
  if (laborMonthly <= 0 || totalEmployees <= 0 || hoursPerMonth <= 0 || daysPerMonth <= 0) return 0
  const divisor = totalEmployees * daysPerMonth * hoursPerMonth
  if (divisor <= 0) return 0
  const pctAsNumber = laborMonthly / divisor
  return Math.round((pctAsNumber / 100) * 10000) / 10000
}

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export type CalcType = 'INDUSTRIALIZACAO' | 'REVENDA' | 'SERVICO'

export interface PricingInput {
  calcType: CalcType

  // -- CMV ingredients --
  /** Sum of product_items costs for 1 batch/recipe (R$). */
  totalItemsCost: number

  /**
   * Units produced per 1 batch/recipe (>= 1).
   * e.g. a recipe yields 10 cupcakes → yieldQuantity = 10.
   */
  yieldQuantity: number

  // -- Labor (monetary, from tenant_expense_config) --
  /** Total monthly cost of productive labor (R$). */
  laborCostMonthly: number

  /** Number of productive employees (informational; not used in calculation). */
  numProductiveEmployees: number

  /** Total productive minutes available per month (entire company). */
  monthlyWorkloadMinutes: number

  /** Minutes of productive labor consumed by this product/service. */
  productWorkloadMinutes: number

  // -- Structure (read-only, from tenant_expense_config) --
  /**
   * Fixed + variable + financial expenses as decimal.
   * For REVENDA, caller must include any labor overhead percentage here.
   */
  structurePct: number

  // -- Tax (read-only) --
  /** Single effective tax rate as decimal (combined DAS / ICMS+PIS+COFINS / etc). */
  taxPct: number

  // -- Editable per product --
  /** Sales commission as decimal. */
  commissionPct: number
  /** Desired profit margin as decimal. */
  profitPct: number
}

export interface PricingResult {
  isValid: boolean
  validationErrors: string[]

  // CMV
  cmvTotal: number
  cmvUnit: number
  /**
   * R$ of productive labor for this product.
   * For INDUSTRIALIZACAO/SERVICO: equals productiveLaborCost (already inside cmvUnit).
   * For REVENDA: always 0 (labor overhead is embedded in structureValue).
   */
  laborValue: number
  /** % productive labor represents over priceUnit (for display). */
  laborPctShown: number

  // Percentages echoed back (decimal)
  structurePct: number
  taxPct: number
  commissionPct: number
  profitPct: number

  /** Productive labor cost in R$ for this product (productWorkloadMinutes × costPerMinute). */
  productiveLaborCost: number

  /** 1 - (structurePct + taxPct + commissionPct + profitPct). Must be > 0. */
  coefficient: number

  // Prices
  priceUnit: number
  priceTotal: number

  // Breakdown (absolute R$ values derived from priceUnit × each %)
  structureValue: number
  taxValue: number
  commissionValue: number
  profitValue: number
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

const round2 = (v: number): number => Math.round(v * 100) / 100

function emptyResult(errors: string[]): PricingResult {
  return {
    isValid: false,
    validationErrors: errors,
    cmvTotal: 0,
    cmvUnit: 0,
    productiveLaborCost: 0,
    laborValue: 0,
    laborPctShown: 0,
    structurePct: 0,
    taxPct: 0,
    commissionPct: 0,
    profitPct: 0,
    coefficient: 0,
    priceUnit: 0,
    priceTotal: 0,
    structureValue: 0,
    taxValue: 0,
    commissionValue: 0,
    profitValue: 0,
  }
}

// ---------------------------------------------------------------------------
// Engine
// ---------------------------------------------------------------------------

/**
 * Calculates selling price using the coefficient method (por dentro):
 *   priceUnit = cmvUnit / coefficient
 *   coefficient = 1 − (structurePct + taxPct + commissionPct + profitPct)
 *
 * All percentages are applied over the final price, not over CMV.
 *
 * Labor handling:
 *  - INDUSTRIALIZACAO / SERVICO: productive labor enters CMV directly.
 *  - REVENDA: productive labor is zero; any overhead must be pre-included in structurePct.
 */
export function calculatePricing(input: PricingInput): PricingResult {
  const errors: string[] = []

  if (input.yieldQuantity < 1) {
    errors.push('yieldQuantity deve ser >= 1')
  }

  if (input.totalItemsCost < 0) {
    errors.push('totalItemsCost não pode ser negativo')
  }

  if (errors.length > 0) {
    return emptyResult(errors)
  }

  const {
    calcType,
    totalItemsCost,
    yieldQuantity,
    laborCostMonthly,
    monthlyWorkloadMinutes,
    productWorkloadMinutes,
    structurePct,
    taxPct,
    commissionPct,
    profitPct,
  } = input

  // Step 1 — custo de MO produtiva deste produto (R$)
  const costPerMinute = monthlyWorkloadMinutes > 0
    ? laborCostMonthly / monthlyWorkloadMinutes
    : 0
  const productiveLaborCost = round2(productWorkloadMinutes * costPerMinute)

  // Step 2 — CMV por unidade
  const itemsCostPerUnit = round2(totalItemsCost / yieldQuantity)

  // INDUSTRIALIZACAO e SERVICO: MO produtiva entra no CMV
  // REVENDA: MO produtiva é zero; overhead de mão de obra está em structurePct
  const cmvUnit = calcType === 'REVENDA'
    ? itemsCostPerUnit
    : round2(itemsCostPerUnit + productiveLaborCost)
  const cmvTotal = round2(cmvUnit * yieldQuantity)

  // Step 3 — coeficiente (todos os % incidem sobre o preço final, por dentro)
  // Não aplicar round2 aqui para preservar precisão na divisão.
  const coefficient = 1 - (structurePct + taxPct + commissionPct + profitPct)

  // Step 4 — validar coeficiente
  if (coefficient <= 0) {
    return emptyResult(['Coeficiente <= 0: a soma dos percentuais excede 100%'])
  }

  // Step 5 — preço unitário e total
  const priceUnit = round2(cmvUnit / coefficient)
  const priceTotal = round2(priceUnit * yieldQuantity)

  // Step 6 — valores absolutos (para exibição no DRE)
  const structureValue = round2(priceUnit * structurePct)
  const taxValue       = round2(priceUnit * taxPct)
  const commissionValue = round2(priceUnit * commissionPct)
  const profitValue    = round2(priceUnit * profitPct)

  // Para REVENDA: MO é parte da estrutura (já em structureValue); não aparece como linha separada.
  // Para INDUSTRIALIZACAO/SERVICO: MO produtiva já entrou no CMV como productiveLaborCost.
  const laborValue = calcType === 'REVENDA' ? 0 : round2(productiveLaborCost)

  // laborPctShown: % que MO produtiva representa no preço final (para exibição)
  const laborPctShown = priceUnit > 0
    ? Math.round((productiveLaborCost / priceUnit) * 10000) / 10000
    : 0

  return {
    isValid: true,
    validationErrors: [],
    cmvTotal,
    cmvUnit,
    productiveLaborCost,
    laborValue,
    laborPctShown,
    structurePct,
    taxPct,
    commissionPct,
    profitPct,
    coefficient,
    priceUnit,
    priceTotal,
    structureValue,
    taxValue,
    commissionValue,
    profitValue,
  }
}

// ---------------------------------------------------------------------------
// Workload normaliser (used by UI before calling calculatePricing)
// ---------------------------------------------------------------------------

export type WorkloadUnit = 'MINUTES' | 'HOURS' | 'DAYS' | 'ACTIVITIES'

/**
 * Converts a workload value to minutes so the engine always works in minutes.
 * For SERVICO with HOURS/DAYS the raw value is kept (service measures differently).
 */
export function normalizeToMinutes(
  value: number,
  unit: WorkloadUnit,
  isService: boolean,
): number {
  if (isService) return value // service uses raw unit as-is

  switch (unit) {
    case 'HOURS':
      return value * 60
    case 'DAYS':
      return value * 480 // 8h * 60min
    case 'MINUTES':
    case 'ACTIVITIES':
    default:
      return value
  }
}
